export const domain = "https://pizzaapi.pythonanywhere.com"
export const appMode = "/api"
export const login = "/token/"
export const productsListUrl="/product/all"
export const productAddUrl="/product/all/"
export const categoryAddUrl="/category/all/"
export const categoriesListUrl="/category/all"